name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS \
          --password-stdin 152253548298.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t todo-app .
          docker tag todo-app:latest 152253548298.dkr.ecr.us-east-1.amazonaws.com/todo-app:latest
          docker push 152253548298.dkr.ecr.us-east-1.amazonaws.com/todo-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 152253548298.dkr.ecr.us-east-1.amazonaws.com
            docker pull 152253548298.dkr.ecr.us-east-1.amazonaws.com/todo-app:latest
            docker stop todo || true
            docker rm todo || true
            docker run -d --name todo -p 80:8000 -e DB_NAME=postgres -e DB_USER=postgres -e DB_PASSWORD=iloverpgcd7b4bsks -e DB_HOST=todo-db.cqtmoagqey6t.us-east-1.rds.amazonaws.com 152253548298.dkr.ecr.us-east-1.amazonaws.com/todo-app:latest
